export const PATTERNS = {
  '4-7-8': {
    label: '4-7-8 Breathing',
    inhale: 4,
    holdIn: 7,
    exhale: 8,
    holdOut: 0,
    description: 'Classic relaxation technique',
    difficulty: 'intermediate',
  },
  box: {
    label: 'Box Breathing',
    inhale: 4,
    holdIn: 4,
    exhale: 4,
    holdOut: 4,
    description: 'Used by Navy SEALs',
    difficulty: 'intermediate',
  },
  relaxed: {
    label: 'Relaxed',
    inhale: 4,
    holdIn: 2,
    exhale: 6,
    holdOut: 0,
    description: 'Gentle calming breath',
    difficulty: 'easy',
  },
  energizing: {
    label: 'Energizing',
    inhale: 2,
    holdIn: 2,
    exhale: 4,
    holdOut: 0,
    description: 'Quick energy boost',
    difficulty: 'easy',
  },
  deepCalm: {
    label: 'Deep Calm',
    inhale: 5,
    holdIn: 5,
    exhale: 5,
    holdOut: 5,
    description: 'Deep relaxation',
    difficulty: 'intermediate',
  },
  coherent: {
    label: 'Coherent',
    inhale: 5,
    holdIn: 0,
    exhale: 5,
    holdOut: 0,
    description: 'Heart-brain coherence',
    difficulty: 'easy',
  },
  wimHof: {
    label: 'Wim Hof',
    inhale: 2,
    holdIn: 0,
    exhale: 2,
    holdOut: 10,
    description: 'Cold exposure prep',
    difficulty: 'advanced',
  },
  beginner: {
    label: 'Beginner 2-1-4',
    inhale: 2,
    holdIn: 1,
    exhale: 4,
    holdOut: 0,
    description: 'Great for starters',
    difficulty: 'easy',
  },
};

export const PHASES = ['inhale', 'holdIn', 'exhale', 'holdOut'];

export const PHASE_LABELS = {
  inhale: 'Inhale',
  holdIn: 'Hold',
  exhale: 'Exhale',
  holdOut: 'Hold',
};
